experiment_name: null
name: yolox-m

camid: 0
# mode: image
# path: ~/code/YOLOX/data/image/dog.jpg
mode: video
# path: ~/code/YOLOX/data/video/single_person.mp4
path: ~/code/YOLOX/data/video/multiple_people.mp4
save_result: true

ckpt: weights/yolox_m.pth
device: gpu
exp_file: null

conf: 0.25
nms: 0.45
tsize: 416

fp16: false
fuse: true
legacy: false
trt: false
